version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-node-browsers

    environment:
      TZ: /usr/share/zoneinfo/America/Los_Angeles

    parallelism: 4

    steps:
      - checkout

      - run: echo $CIRCLE_COMPARE_URL | cut -d/ -f7

      - run:
          name: Nodejs Version
          command: node --version

      - run:
          name: Install Packages
          command: yarn install --frozen-lockfile

      - run:
          name: Test Packages
          command: bash ./scripts/circleci/test_entry_point.sh

      - store_artifacts:
          path: ./node_modules.tgz

      - store_artifacts:
          path: ./build.tgz

      - store_artifacts:
          path: ./scripts/error-codes/codes.json
